language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
node_js:
  - 6
before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
script: npm run test-ci
